src/Entity/Academico/Calificacion.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * Calificacion
 *
 * @ORM\Table(name="odontoped_academico.calificacion", indexes={
 *     @ORM\Index(name="fk_calificacion_estudiante_curso", columns={"id_estudiante_curso"}),
 *     @ORM\Index(name="fk_calificacion_evaluacion", columns={"id_evaluacion"}),
 *     @ORM\Index(name="fk_calificacion_grupo", columns={"id_calificacion_grupo"}),
 *     @ORM\Index(name="fk_calificacion_padre", columns={"id_padre"})
 * })
 * @ORM\Entity(repositoryClass="App\Repository\Academico\CalificacionRepository")
 */
class Calificacion
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nota", type="decimal", precision=8, scale=2, nullable=false)
     */
    private $nota;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fecha", type="date", nullable=false)
     */
    private $fecha;

    /**
     * @var bool
     *
     * @ORM\Column(name="permiso", type="boolean", nullable=false)
     */
    private $permiso = false;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var EstudianteCurso
     *
     * @ORM\ManyToOne(targetEntity="EstudianteCurso")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_estudiante_curso", referencedColumnName="id")
     * })
     */
    private $estudiante_curso;

    /**
     * @var Evaluacion
     *
     * @ORM\ManyToOne(targetEntity="Evaluacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_evaluacion", referencedColumnName="id")
     * })
     */
    private $evaluacion;

    /**
     * @var CalificacionGrupo
     *
     * @ORM\ManyToOne(targetEntity="CalificacionGrupo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_calificacion_grupo", referencedColumnName="id")
     * })
     */
    private $calificacion_grupo;

    /**
     * @var Calificacion
     *
     * @ORM\ManyToOne(targetEntity="Calificacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_padre", referencedColumnName="id")
     * })
     */
    private $padre;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Academico\CalificacionPenalizacion", mappedBy="calificacion")
     */
    private $penalizaciones;


    public function __construct()
    {
        $this->penalizaciones = array();
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNota(): ?string
    {
        return $this->nota;
    }

    /**
     * @param string $nota
     * @return Calificacion
     */
    public function setNota(string $nota): Calificacion
    {
        $this->nota = $nota;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getFecha(): ?\DateTime
    {
        return $this->fecha;
    }

    /**
     * @param \DateTime $fecha
     * @return Calificacion
     */
    public function setFecha(\DateTime $fecha): Calificacion
    {
        $this->fecha = $fecha;
        return $this;
    }

    /**
     * @return bool
     */
    public function isPermiso(): ?bool
    {
        return $this->permiso;
    }

    /**
     * @param bool $permiso
     * @return Calificacion
     */
    public function setPermiso(bool $permiso): Calificacion
    {
        $this->permiso = $permiso;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return Calificacion
     */
    public function setCreado(\DateTime $creado): Calificacion
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return EstudianteCurso
     */
    public function getEstudianteCurso(): ?EstudianteCurso
    {
        return $this->estudiante_curso;
    }

    /**
     * @param EstudianteCurso $estudiante_curso
     * @return Calificacion
     */
    public function setEstudianteCurso(EstudianteCurso $estudiante_curso): Calificacion
    {
        $this->estudiante_curso = $estudiante_curso;
        return $this;
    }

    /**
     * @return Evaluacion
     */
    public function getEvaluacion(): ?Evaluacion
    {
        return $this->evaluacion;
    }

    /**
     * @param Evaluacion $evaluacion
     * @return Calificacion
     */
    public function setEvaluacion(Evaluacion $evaluacion): Calificacion
    {
        $this->evaluacion = $evaluacion;
        return $this;
    }

    /**
     * @return CalificacionGrupo
     */
    public function getCalificacionGrupo(): ?CalificacionGrupo
    {
        return $this->calificacion_grupo;
    }

    /**
     * @param CalificacionGrupo $calificacion_grupo
     * @return Calificacion
     */
    public function setCalificacionGrupo(CalificacionGrupo $calificacion_grupo): Calificacion
    {
        $this->calificacion_grupo = $calificacion_grupo;
        return $this;
    }

    /**
     * @return Calificacion
     */
    public function getPadre(): ?Calificacion
    {
        return $this->padre;
    }

    /**
     * @param Calificacion $padre
     * @return Calificacion
     */
    public function setPadre(Calificacion $padre): Calificacion
    {
        $this->padre = $padre;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPenalizaciones()
    {
        return $this->penalizaciones;
    }

    /**
     * @param mixed $penalizaciones
     */
    public function setPenalizaciones($penalizaciones): void
    {
        $this->penalizaciones = $penalizaciones;
    }


}

src/Entity/Academico/CalificacionGrupo.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * CalificacionGrupo
 *
 * @ORM\Table(name="odontoped_academico.calificacion_grupo", indexes={
 *     @ORM\Index(name="fk_grupo_calificacion", columns={"id_grupo"}),
 *     @ORM\Index(name="fk_calificacion_grupo_evaluacion", columns={"id_evaluacion"}),
 *     @ORM\Index(name="fk_calificacion_grupo_padre", columns={"id_padre"})
 * })
 * @ORM\Entity
 */
class CalificacionGrupo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nota", type="decimal", precision=8, scale=2, nullable=false)
     */
    private $nota;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fecha", type="date", nullable=false)
     */
    private $fecha;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var \App\Entity\Rotacion\Grupo
     *
     * @ORM\ManyToOne(targetEntity="\App\Entity\Rotacion\Grupo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_grupo", referencedColumnName="id")
     * })
     */
    private $grupo;

    /**
     * @var Evaluacion
     *
     * @ORM\ManyToOne(targetEntity="Evaluacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_evaluacion", referencedColumnName="id")
     * })
     */
    private $evaluacion;

    /**
     * @var CalificacionGrupo
     *
     * @ORM\ManyToOne(targetEntity="CalificacionGrupo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_padre", referencedColumnName="id")
     * })
     */
    private $padre;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNota(): ?string
    {
        return $this->nota;
    }

    /**
     * @param string $nota
     * @return CalificacionGrupo
     */
    public function setNota(string $nota): CalificacionGrupo
    {
        $this->nota = $nota;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getFecha(): ?\DateTime
    {
        return $this->fecha;
    }

    /**
     * @param \DateTime $fecha
     * @return CalificacionGrupo
     */
    public function setFecha(\DateTime $fecha): CalificacionGrupo
    {
        $this->fecha = $fecha;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return CalificacionGrupo
     */
    public function setCreado(\DateTime $creado): CalificacionGrupo
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return \App\Entity\Rotacion\Grupo
     */
    public function getGrupo(): ?\App\Entity\Rotacion\Grupo
    {
        return $this->grupo;
    }

    /**
     * @param \App\Entity\Rotacion\Grupo $grupo
     * @return CalificacionGrupo
     */
    public function setGrupo(\App\Entity\Rotacion\Grupo $grupo): CalificacionGrupo
    {
        $this->grupo = $grupo;
        return $this;
    }

    /**
     * @return Evaluacion
     */
    public function getEvaluacion(): ?Evaluacion
    {
        return $this->evaluacion;
    }

    /**
     * @param Evaluacion $evaluacion
     * @return CalificacionGrupo
     */
    public function setEvaluacion(Evaluacion $evaluacion): CalificacionGrupo
    {
        $this->evaluacion = $evaluacion;
        return $this;
    }

    /**
     * @return CalificacionGrupo
     */
    public function getPadre(): ?CalificacionGrupo
    {
        return $this->padre;
    }

    /**
     * @param CalificacionGrupo $padre
     * @return CalificacionGrupo
     */
    public function setPadre(CalificacionGrupo $padre): CalificacionGrupo
    {
        $this->padre = $padre;
        return $this;
    }


}

src/Entity/Academico/CalificacionPenalizacion.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * CalificacionPenalizacion
 *
 * @ORM\Table(name="odontoped_academico.calificacion_penalizacion", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="unique_calificacion_penalizacion", columns={"id_calificacion", "id_penalizacion"})
 * }, indexes={
 *     @ORM\Index(name="fk_calificacion_penalizacion", columns={"id_calificacion"}),
 *     @ORM\Index(name="fk_penalizacion_calificacion", columns={"id_penalizacion"})
 * })
 * @ORM\Entity
 */
class CalificacionPenalizacion
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var Calificacion
     *
     * @ORM\ManyToOne(targetEntity="Calificacion", inversedBy="penalizaciones")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_calificacion", referencedColumnName="id")
     * })
     */
    private $calificacion;

    /**
     * @var Penalizacion
     *
     * @ORM\ManyToOne(targetEntity="Penalizacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_penalizacion", referencedColumnName="id")
     * })
     */
    private $penalizacion;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return CalificacionPenalizacion
     */
    public function setCreado(\DateTime $creado): CalificacionPenalizacion
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return Calificacion
     */
    public function getCalificacion(): ?Calificacion
    {
        return $this->calificacion;
    }

    /**
     * @param Calificacion $calificacion
     * @return CalificacionPenalizacion
     */
    public function setCalificacion(Calificacion $calificacion): CalificacionPenalizacion
    {
        $this->calificacion = $calificacion;
        return $this;
    }

    /**
     * @return Penalizacion
     */
    public function getPenalizacion(): ?Penalizacion
    {
        return $this->penalizacion;
    }

    /**
     * @param Penalizacion $penalizacion
     * @return CalificacionPenalizacion
     */
    public function setPenalizacion(Penalizacion $penalizacion): CalificacionPenalizacion
    {
        $this->penalizacion = $penalizacion;
        return $this;
    }


}

src/Entity/Academico/EstudianteCurso.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * EstudianteCurso
 *
 * @ORM\Table(name="odontoped_academico.estudiante_curso", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="unique_estudiante_curso", columns={"id_estudiante_plan_estudio", "id_curso", "id_periodo_ciclo"})
 * }, indexes={
 *     @ORM\Index(name="fk_estudiante_curso_plan_estudio", columns={"id_estudiante_plan_estudio"}),
 *     @ORM\Index(name="fk_estudiante_curso", columns={"id_curso"}),
 *     @ORM\Index(name="fk_estudiante_curso_periodo_ciclo", columns={"id_periodo_ciclo"}),
 *     @ORM\Index(name="fk_estudiante_curso_estado", columns={"id_estudiante_estado"})
 * })
 * @ORM\Entity(repositoryClass="App\Repository\Academico\EstudianteCursoRepository")
 */
class EstudianteCurso
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var EstudiantePlanEstudio
     *
     * @ORM\ManyToOne(targetEntity="EstudiantePlanEstudio")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_estudiante_plan_estudio", referencedColumnName="id")
     * })
     */
    private $estudiante_plan_estudio;

    /**
     * @var Curso
     *
     * @ORM\ManyToOne(targetEntity="Curso")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_curso", referencedColumnName="id")
     * })
     */
    private $curso;

    /**
     * @var PeriodoCiclo
     *
     * @ORM\ManyToOne(targetEntity="PeriodoCiclo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_periodo_ciclo", referencedColumnName="id")
     * })
     */
    private $periodo_ciclo;

    /**
     * @var EstudianteEstado
     *
     * @ORM\ManyToOne(targetEntity="EstudianteEstado")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_estudiante_estado", referencedColumnName="id")
     * })
     */
    private $estudiante_estado;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return EstudianteCurso
     */
    public function setCreado(\DateTime $creado): EstudianteCurso
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return EstudiantePlanEstudio
     */
    public function getEstudiantePlanEstudio(): ?EstudiantePlanEstudio
    {
        return $this->estudiante_plan_estudio;
    }

    /**
     * @param EstudiantePlanEstudio $estudiante_plan_estudio
     * @return EstudianteCurso
     */
    public function setEstudiantePlanEstudio(EstudiantePlanEstudio $estudiante_plan_estudio): EstudianteCurso
    {
        $this->estudiante_plan_estudio = $estudiante_plan_estudio;
        return $this;
    }

    /**
     * @return Curso
     */
    public function getCurso(): ?Curso
    {
        return $this->curso;
    }

    /**
     * @param Curso $curso
     * @return EstudianteCurso
     */
    public function setCurso(Curso $curso): EstudianteCurso
    {
        $this->curso = $curso;
        return $this;
    }

    /**
     * @return PeriodoCiclo
     */
    public function getPeriodoCiclo(): ?PeriodoCiclo
    {
        return $this->periodo_ciclo;
    }

    /**
     * @param PeriodoCiclo $periodo_ciclo
     * @return EstudianteCurso
     */
    public function setPeriodoCiclo(PeriodoCiclo $periodo_ciclo): EstudianteCurso
    {
        $this->periodo_ciclo = $periodo_ciclo;
        return $this;
    }

    /**
     * @return EstudianteEstado
     */
    public function getEstudianteEstado(): ?EstudianteEstado
    {
        return $this->estudiante_estado;
    }

    /**
     * @param EstudianteEstado $estudiante_estado
     * @return EstudianteCurso
     */
    public function setEstudianteEstado(EstudianteEstado $estudiante_estado): EstudianteCurso
    {
        $this->estudiante_estado = $estudiante_estado;
        return $this;
    }

    /**
     * @return null|string
     */
    public function __toString(): ?string
    {
        return (string)$this->curso;
    }

}

templates/academico/evaluaciones/evaluacion_calculada_individual.html.twig
<input id="idEvaluacion" type="hidden" value="{{ evaluacion.id }}" />

<table class="table table-striped table-bordered table-sm table-responsive-sm">
    <thead>
    <tr>
        <th>Carnet</th>
        <th>Nombre</th>
        <th class="align-middle">Nota</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    {% for calificacion in calificaciones %}
        <tr>
            <td>{{ calificacion.estudianteCurso.estudiantePlanEstudio.estudiante.carnet }}</td>
            <td>{{ calificacion.estudianteCurso.estudiantePlanEstudio.estudiante.persona.nombre }}</td>
            <td><span class="badge badge-dark tada animated" style="font-size:15px;width:50px;height:25px;" data-toggle="tooltip" t>{{ calificacion.nota }}</span></td>
            <td> <button onclick="onLoadDetalle({{calificacion.estudianteCurso.id  }})" class="btn btn-primary btn-block" type="button">Detalle</button>
            </td>
        </tr>
    {% endfor %}

    </tbody>
</table>

templates/academico/evaluaciones/evaluacion_calculada_nota_estudiante.html.twig
<div class="modal-dialog" role="document">
    <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Estudiante: {{ calificacionPadre.estudianteCurso.estudiantePlanEstudio.estudiante.persona.nombreCompleto  }}</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">

                <input id="evaluacionPadre" type="hidden" value="{{ calificacionPadre.evaluacion.id }}" />
                <input id="estudianteCurso" type="hidden" value="{{ calificacionPadre.estudianteCurso.id }}" />

                <table class="table table-striped table-bordered table-sm" id="notasGrupo">
                    <thead>
                    <tr>
                        <th>Criterio</th>
                        <th class="align-middle">Nota</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for calificacion in criterios %}
                        <tr>
                            <td>{{ calificacion.evaluacion.nombre }}&nbsp;</td>
                            <td><input type="number" lang="en"  min="0.0" max="10.0" step="0.01" value="{{ calificacion.nota }}" style="width:100%;" onchange="calcularNotaGrupo()" ></td>
                            <td style="display:none;">{{ calificacion.evaluacion.ponderacion}}</td>
                            <td style="display:none;">{{ calificacion.evaluacion.id}}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="table-info">
                        <td><strong>Nota</strong></td>
                        <td><span class="badge badge-info tada animated" id="totalGroup" style="font-size:19px;width:50px;height:29px;" data-toggle="tooltip" >{{ calificacionPadre.nota }}</span><br></td>
                    </tr>
                    </tfoot>
                </table>

            </div>
            <div class="modal-footer">
                <button class="btn btn-light" type="button" data-dismiss="modal">Cerrar</button>
                <button class="btn btn-primary" onclick="updateCalculadaIndividual()" type="submit">Guardar</button>
            </div>
            <div class="alert alert-danger" id="alert_template" style="display: none;">
                <button type="button" class="close">×</button>
            </div>
    </div>
</div>

templates/academico/evaluaciones/evaluacion_calculada_nota_grupo.html.twig
<input id="evaluacionPadre" type="hidden" value="{{ grupo.evaluacion.id }}"/>

<table class="table table-striped table-bordered table-sm" id="notasGrupo">
    <thead>
    <tr>
        <th>Criterio</th>
        <th class="align-middle">Nota</th>
    </tr>
    </thead>
    <tbody>
    {% for calificacion in criterios %}
        <tr>
            <td>{{ calificacion.evaluacion.nombre }}&nbsp;</td>
            <td><input type="number" lang="en" min="0.0" max="10.0" step="0.01" value="{{ calificacion.nota }}" style="width:100%;"
                       onchange="calcularNotaGrupo()"></td>
            <td style="display:none;">{{ calificacion.evaluacion.ponderacion }}</td>
            <td style="display:none;">{{ calificacion.evaluacion.id }}</td>

        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr class="table-info">
        <td><strong>Nota</strong></td>
        <td><span class="badge badge-info tada animated" id="totalGroup" style="font-size:19px;width:50px;height:29px;"
                  data-toggle="tooltip">{{ grupo.nota }}</span><br></td>
    </tr>
    </tfoot>
</table>

{% if not nuevo %}

    <table class="table table-striped table-bordered table-sm">
        <thead>
        <tr>
            <th>Carnet</th>
            <th>Nombre</th>
            <th>Penalizaciones</th>
            <th class="align-middle">Nota</th>
            <th>Penalizar</th>
        </tr>
        </thead>
        <tbody>
        {% for calificacion in calificaciones %}
            <tr>
                <td>{{ calificacion.estudianteCurso.estudiantePlanEstudio.estudiante.carnet }}</td>
                <td>{{ calificacion.estudianteCurso.estudiantePlanEstudio.estudiante.persona.nombre }}</td>
                <td>
                    <ul style="padding-left:15px;font-size:14px;margin-bottom:0px;">
                        {% for calificacionPenalizacion in calificacion.penalizaciones %}
                            <li>{{ calificacionPenalizacion.penalizacion.nombre }}&nbsp;
                                <button onclick="removePenalizacion({{ calificacionPenalizacion.id }})" class="btn btn-danger active btn-sm" type="button"
                                        style="height:20px;margin-right:0px;padding-top:0px;"><i class="fa fa-minus"></i></button>
                                <br></li>
                        {% endfor %}
                    </ul>
                </td>
                <td><span class="badge badge-dark tada animated" style="font-size:15px;width:50px;height:25px;"
                          data-toggle="tooltip">{{ calificacion.nota }}</span></td>
                <td>
                    <div class="btn-group" role="group">
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false" type="button"><i
                                        class="fa fa-plus" style="font-size:16px;"></i>&nbsp;
                            </button>
                            <div class="dropdown-menu" role="menu">
                                {% for penalizacion in penalizaciones %}
                                    <a class="dropdown-item" role="presentation"
                                       onclick="addPenalizacion({{ penalizacion.id }},{{ calificacion.id }}); return false;"
                                       href="#">{{ penalizacion.nombre }} </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% else %}
    <table class="table table-striped table-bordered table-sm">
        <thead>
        <tr>
            <th>Carnet</th>
            <th>Nombre</th>
        </tr>
        </thead>
        <tbody>
        {% for estudiante in estudiantes %}
            <tr>
                <td>{{ estudiante.estudianteCurso.estudiantePlanEstudio.estudiante.carnet }}</td>
                <td>{{ estudiante.estudianteCurso.estudiantePlanEstudio.estudiante.persona.nombre }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

templates/academico/evaluaciones/evaluacion_diaria.html.twig
<div class="form-group">
    <label for="fechaCalificar">Fecha&nbsp;</label>
    <input id="fechaCalificar" name="fechaCalificar" class="form-control-sm" type="date" value="{{ fecha? fecha|date('Y-m-d') : null }}"
           onchange="onSelectItem($('#jqxTree').jqxTree('getSelectedItem'));">
</div>
<div class="col">
    <div class="table-responsive table-bordered">
        <table class="table table-striped table-bordered table-sm">
            <thead>
            <tr>
                <th>Carnet</th>
                <th>Nombre</th>
                <th class="align-middle">Nota</th>
                <th>Permiso</th>
            </tr>
            </thead>
            <tbody>
            {% for estudiante in estudiantes %}
                <tr>
                    <td>{{ estudiante.estudiantePlanEstudio.estudiante.carnet }}</td>
                    <td> {{ estudiante.estudiantePlanEstudio.estudiante.persona.nombreCompleto }}</td>
                    <td><input type="number" disabled style="width:100%;" step="0.01" min="0" max="10"></td>
                    <td><span class="float-right switch switch-sm"><input type="checkbox" id="switch-sm3" class="switch"><label
                                    for="switch-sm3"><br></label></span></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/academico/evaluaciones/evaluacion_unica.html.twig
<input id="idEvaluacion" type="hidden" value="{{ evaluacion.id }}"/>
<div class="col">
    <div class="form-group">
        <button onclick="update()" class="btn btn-primary form-control" type="button">Guardar</button>
    </div>
</div>
<div class="col">
    <div class="table-responsive table-bordered">
        <table id="tblUnica" class="table table-striped table-bordered table-sm">
            <thead>
            <tr>
                <th>Carnet</th>
                <th>Nombre</th>
                <th class="align-middle">Nota</th>
            </tr>
            </thead>
            <tbody>
            {% for calificacion in calificaciones %}
                <tr>
                    <td>{{ calificacion.estudianteCurso.estudiantePlanEstudio.estudiante.carnet }}</td>
                    <td> {{ calificacion.estudianteCurso.estudiantePlanEstudio.estudiante.persona.nombreCompleto }}</td>
                    <td><input maxlength="5" type="number" lang="en" max="10.00" min="0.00" step="0.01" value="{{ calificacion.nota }}"
                               style="width:100%;"></td>
                    <td style="display:none;">{{ calificacion.estudianteCurso.id }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>