src/Entity/Academico/Calificacion.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * Calificacion
 *
 * @ORM\Table(name="odontoped_academico.calificacion", indexes={
 *     @ORM\Index(name="fk_calificacion_estudiante_curso", columns={"id_estudiante_curso"}),
 *     @ORM\Index(name="fk_calificacion_evaluacion", columns={"id_evaluacion"}),
 *     @ORM\Index(name="fk_calificacion_grupo", columns={"id_calificacion_grupo"}),
 *     @ORM\Index(name="fk_calificacion_padre", columns={"id_padre"})
 * })
 * @ORM\Entity(repositoryClass="App\Repository\Academico\CalificacionRepository")
 */
class Calificacion
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nota", type="decimal", precision=8, scale=2, nullable=false)
     */
    private $nota;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fecha", type="date", nullable=false)
     */
    private $fecha;

    /**
     * @var bool
     *
     * @ORM\Column(name="permiso", type="boolean", nullable=false)
     */
    private $permiso = false;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var EstudianteCurso
     *
     * @ORM\ManyToOne(targetEntity="EstudianteCurso")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_estudiante_curso", referencedColumnName="id")
     * })
     */
    private $estudiante_curso;

    /**
     * @var Evaluacion
     *
     * @ORM\ManyToOne(targetEntity="Evaluacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_evaluacion", referencedColumnName="id")
     * })
     */
    private $evaluacion;

    /**
     * @var CalificacionGrupo
     *
     * @ORM\ManyToOne(targetEntity="CalificacionGrupo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_calificacion_grupo", referencedColumnName="id")
     * })
     */
    private $calificacion_grupo;

    /**
     * @var Calificacion
     *
     * @ORM\ManyToOne(targetEntity="Calificacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_padre", referencedColumnName="id")
     * })
     */
    private $padre;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Academico\CalificacionPenalizacion", mappedBy="calificacion")
     */
    private $penalizaciones;


    public function __construct()
    {
        $this->penalizaciones = array();
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNota(): ?string
    {
        return $this->nota;
    }

    /**
     * @param string $nota
     * @return Calificacion
     */
    public function setNota(string $nota): Calificacion
    {
        $this->nota = $nota;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getFecha(): ?\DateTime
    {
        return $this->fecha;
    }

    /**
     * @param \DateTime $fecha
     * @return Calificacion
     */
    public function setFecha(\DateTime $fecha): Calificacion
    {
        $this->fecha = $fecha;
        return $this;
    }

    /**
     * @return bool
     */
    public function isPermiso(): ?bool
    {
        return $this->permiso;
    }

    /**
     * @param bool $permiso
     * @return Calificacion
     */
    public function setPermiso(bool $permiso): Calificacion
    {
        $this->permiso = $permiso;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return Calificacion
     */
    public function setCreado(\DateTime $creado): Calificacion
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return EstudianteCurso
     */
    public function getEstudianteCurso(): ?EstudianteCurso
    {
        return $this->estudiante_curso;
    }

    /**
     * @param EstudianteCurso $estudiante_curso
     * @return Calificacion
     */
    public function setEstudianteCurso(EstudianteCurso $estudiante_curso): Calificacion
    {
        $this->estudiante_curso = $estudiante_curso;
        return $this;
    }

    /**
     * @return Evaluacion
     */
    public function getEvaluacion(): ?Evaluacion
    {
        return $this->evaluacion;
    }

    /**
     * @param Evaluacion $evaluacion
     * @return Calificacion
     */
    public function setEvaluacion(Evaluacion $evaluacion): Calificacion
    {
        $this->evaluacion = $evaluacion;
        return $this;
    }

    /**
     * @return CalificacionGrupo
     */
    public function getCalificacionGrupo(): ?CalificacionGrupo
    {
        return $this->calificacion_grupo;
    }

    /**
     * @param CalificacionGrupo $calificacion_grupo
     * @return Calificacion
     */
    public function setCalificacionGrupo(CalificacionGrupo $calificacion_grupo): Calificacion
    {
        $this->calificacion_grupo = $calificacion_grupo;
        return $this;
    }

    /**
     * @return Calificacion
     */
    public function getPadre(): ?Calificacion
    {
        return $this->padre;
    }

    /**
     * @param Calificacion $padre
     * @return Calificacion
     */
    public function setPadre(Calificacion $padre): Calificacion
    {
        $this->padre = $padre;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPenalizaciones()
    {
        return $this->penalizaciones;
    }

    /**
     * @param mixed $penalizaciones
     */
    public function setPenalizaciones($penalizaciones): void
    {
        $this->penalizaciones = $penalizaciones;
    }


}

src/Entity/Academico/CalificacionGrupo.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * CalificacionGrupo
 *
 * @ORM\Table(name="odontoped_academico.calificacion_grupo", indexes={
 *     @ORM\Index(name="fk_grupo_calificacion", columns={"id_grupo"}),
 *     @ORM\Index(name="fk_calificacion_grupo_evaluacion", columns={"id_evaluacion"}),
 *     @ORM\Index(name="fk_calificacion_grupo_padre", columns={"id_padre"})
 * })
 * @ORM\Entity
 */
class CalificacionGrupo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nota", type="decimal", precision=8, scale=2, nullable=false)
     */
    private $nota;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fecha", type="date", nullable=false)
     */
    private $fecha;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var \App\Entity\Rotacion\Grupo
     *
     * @ORM\ManyToOne(targetEntity="\App\Entity\Rotacion\Grupo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_grupo", referencedColumnName="id")
     * })
     */
    private $grupo;

    /**
     * @var Evaluacion
     *
     * @ORM\ManyToOne(targetEntity="Evaluacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_evaluacion", referencedColumnName="id")
     * })
     */
    private $evaluacion;

    /**
     * @var CalificacionGrupo
     *
     * @ORM\ManyToOne(targetEntity="CalificacionGrupo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_padre", referencedColumnName="id")
     * })
     */
    private $padre;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNota(): ?string
    {
        return $this->nota;
    }

    /**
     * @param string $nota
     * @return CalificacionGrupo
     */
    public function setNota(string $nota): CalificacionGrupo
    {
        $this->nota = $nota;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getFecha(): ?\DateTime
    {
        return $this->fecha;
    }

    /**
     * @param \DateTime $fecha
     * @return CalificacionGrupo
     */
    public function setFecha(\DateTime $fecha): CalificacionGrupo
    {
        $this->fecha = $fecha;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return CalificacionGrupo
     */
    public function setCreado(\DateTime $creado): CalificacionGrupo
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return \App\Entity\Rotacion\Grupo
     */
    public function getGrupo(): ?\App\Entity\Rotacion\Grupo
    {
        return $this->grupo;
    }

    /**
     * @param \App\Entity\Rotacion\Grupo $grupo
     * @return CalificacionGrupo
     */
    public function setGrupo(\App\Entity\Rotacion\Grupo $grupo): CalificacionGrupo
    {
        $this->grupo = $grupo;
        return $this;
    }

    /**
     * @return Evaluacion
     */
    public function getEvaluacion(): ?Evaluacion
    {
        return $this->evaluacion;
    }

    /**
     * @param Evaluacion $evaluacion
     * @return CalificacionGrupo
     */
    public function setEvaluacion(Evaluacion $evaluacion): CalificacionGrupo
    {
        $this->evaluacion = $evaluacion;
        return $this;
    }

    /**
     * @return CalificacionGrupo
     */
    public function getPadre(): ?CalificacionGrupo
    {
        return $this->padre;
    }

    /**
     * @param CalificacionGrupo $padre
     * @return CalificacionGrupo
     */
    public function setPadre(CalificacionGrupo $padre): CalificacionGrupo
    {
        $this->padre = $padre;
        return $this;
    }


}

src/Entity/Academico/CalificacionPenalizacion.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * CalificacionPenalizacion
 *
 * @ORM\Table(name="odontoped_academico.calificacion_penalizacion", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="unique_calificacion_penalizacion", columns={"id_calificacion", "id_penalizacion"})
 * }, indexes={
 *     @ORM\Index(name="fk_calificacion_penalizacion", columns={"id_calificacion"}),
 *     @ORM\Index(name="fk_penalizacion_calificacion", columns={"id_penalizacion"})
 * })
 * @ORM\Entity
 */
class CalificacionPenalizacion
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var Calificacion
     *
     * @ORM\ManyToOne(targetEntity="Calificacion", inversedBy="penalizaciones")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_calificacion", referencedColumnName="id")
     * })
     */
    private $calificacion;

    /**
     * @var Penalizacion
     *
     * @ORM\ManyToOne(targetEntity="Penalizacion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_penalizacion", referencedColumnName="id")
     * })
     */
    private $penalizacion;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return CalificacionPenalizacion
     */
    public function setCreado(\DateTime $creado): CalificacionPenalizacion
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return Calificacion
     */
    public function getCalificacion(): ?Calificacion
    {
        return $this->calificacion;
    }

    /**
     * @param Calificacion $calificacion
     * @return CalificacionPenalizacion
     */
    public function setCalificacion(Calificacion $calificacion): CalificacionPenalizacion
    {
        $this->calificacion = $calificacion;
        return $this;
    }

    /**
     * @return Penalizacion
     */
    public function getPenalizacion(): ?Penalizacion
    {
        return $this->penalizacion;
    }

    /**
     * @param Penalizacion $penalizacion
     * @return CalificacionPenalizacion
     */
    public function setPenalizacion(Penalizacion $penalizacion): CalificacionPenalizacion
    {
        $this->penalizacion = $penalizacion;
        return $this;
    }


}

src/Entity/Academico/EstudianteCurso.php
<?php

namespace App\Entity\Academico;

use Doctrine\ORM\Mapping as ORM;

/**
 * EstudianteCurso
 *
 * @ORM\Table(name="odontoped_academico.estudiante_curso", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="unique_estudiante_curso", columns={"id_estudiante_plan_estudio", "id_curso", "id_periodo_ciclo"})
 * }, indexes={
 *     @ORM\Index(name="fk_estudiante_curso_plan_estudio", columns={"id_estudiante_plan_estudio"}),
 *     @ORM\Index(name="fk_estudiante_curso", columns={"id_curso"}),
 *     @ORM\Index(name="fk_estudiante_curso_periodo_ciclo", columns={"id_periodo_ciclo"}),
 *     @ORM\Index(name="fk_estudiante_curso_estado", columns={"id_estudiante_estado"})
 * })
 * @ORM\Entity(repositoryClass="App\Repository\Academico\EstudianteCursoRepository")
 */
class EstudianteCurso
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var EstudiantePlanEstudio
     *
     * @ORM\ManyToOne(targetEntity="EstudiantePlanEstudio")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_estudiante_plan_estudio", referencedColumnName="id")
     * })
     */
    private $estudiante_plan_estudio;

    /**
     * @var Curso
     *
     * @ORM\ManyToOne(targetEntity="Curso")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_curso", referencedColumnName="id")
     * })
     */
    private $curso;

    /**
     * @var PeriodoCiclo
     *
     * @ORM\ManyToOne(targetEntity="PeriodoCiclo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_periodo_ciclo", referencedColumnName="id")
     * })
     */
    private $periodo_ciclo;

    /**
     * @var EstudianteEstado
     *
     * @ORM\ManyToOne(targetEntity="EstudianteEstado")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_estudiante_estado", referencedColumnName="id")
     * })
     */
    private $estudiante_estado;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return EstudianteCurso
     */
    public function setCreado(\DateTime $creado): EstudianteCurso
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return EstudiantePlanEstudio
     */
    public function getEstudiantePlanEstudio(): ?EstudiantePlanEstudio
    {
        return $this->estudiante_plan_estudio;
    }

    /**
     * @param EstudiantePlanEstudio $estudiante_plan_estudio
     * @return EstudianteCurso
     */
    public function setEstudiantePlanEstudio(EstudiantePlanEstudio $estudiante_plan_estudio): EstudianteCurso
    {
        $this->estudiante_plan_estudio = $estudiante_plan_estudio;
        return $this;
    }

    /**
     * @return Curso
     */
    public function getCurso(): ?Curso
    {
        return $this->curso;
    }

    /**
     * @param Curso $curso
     * @return EstudianteCurso
     */
    public function setCurso(Curso $curso): EstudianteCurso
    {
        $this->curso = $curso;
        return $this;
    }

    /**
     * @return PeriodoCiclo
     */
    public function getPeriodoCiclo(): ?PeriodoCiclo
    {
        return $this->periodo_ciclo;
    }

    /**
     * @param PeriodoCiclo $periodo_ciclo
     * @return EstudianteCurso
     */
    public function setPeriodoCiclo(PeriodoCiclo $periodo_ciclo): EstudianteCurso
    {
        $this->periodo_ciclo = $periodo_ciclo;
        return $this;
    }

    /**
     * @return EstudianteEstado
     */
    public function getEstudianteEstado(): ?EstudianteEstado
    {
        return $this->estudiante_estado;
    }

    /**
     * @param EstudianteEstado $estudiante_estado
     * @return EstudianteCurso
     */
    public function setEstudianteEstado(EstudianteEstado $estudiante_estado): EstudianteCurso
    {
        $this->estudiante_estado = $estudiante_estado;
        return $this;
    }

    /**
     * @return null|string
     */
    public function __toString(): ?string
    {
        return (string)$this->curso;
    }

}

templates/academico/estudiante/cargar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cargar Nómina{% endblock %}


{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/myestilos/botonFlotante.css') }}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{{ path('estudiantes_parametros') }}">Estudiantes</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="#">Cargar Nómina</a></li>
{% endblock %}

{% block content %}
    <h2>Cargar Nómina de Estudiantes</h2>
    <br>

    <a href="{{ asset('file/nomina_formato.csv') }}"><i class="fa fa-download fa-fw"></i> Descargar formato</a>
    <br><br>

    <div class="row">
        <div class="col-sm-12 col-md-6">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary"><i class="fa fa-upload fa-fw"></i>Cargar</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/bs-custom-file-input.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            bsCustomFileInput.init()
        })
    </script>
{% endblock %}

templates/academico/estudiante/gestion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Estudiantes{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/dataTables.bootstrap4.min.css') }}">
{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{{ path('estudiantes_parametros') }}">Nomina General</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{ path('estudiante_nomina') }}">Nomina Oficial</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="#">Gestión de Nómina Oficial</a></li>
{% endblock %}
{% block content %}
    <div class="col-md-12 offset-md-0" style="margin-top:25px;margin-left:-6px;">
     {% if estudiantes_periodos %}
        <a class="btn btn-info" href="{{ path('estudiante_estado',{"id":curso.id,"periodo":periodo.id}) }}" style="float: right">
            <i class="fa fa-graduation-cap"></i> Aprobar Todos</a>
     {% endif %}
        <h3>{{ curso.nombre }}&nbsp;<br></h3>
        <h5 class="text-muted">{% if periodo is defined %}{{ periodo.periodo.nombre }}{% endif %} &nbsp;| Numero de estudiantes: {{ estudiantes_periodos|length }}</h5>
    </div>
    {% if estudiantes_periodos %}
        <div class="row">

            <div class="col-md-3">
            </div>
            <div class="col-md-3">
            </div>
            <div class="col-md-3" style="text-align: right">
                <h6 class="text-muted" style="margin-top: 10px">Filtro por Estados:</h6>
            </div>

            {#{{ dump(cursosDeCicloPerido[1]) }}#}
            {#{% if (key==0) %}selected {% endif %}#}
            <div class="col-3" style="float: left;"><select data-column="4"  class="filter-select form-control-sm" style="margin-top:5px;width:100%;">
                    <option value=""   >Estados del Curso</option>
                    {% for key,estado in estados %}
                        <option value="{{ estado.codigo }}" >{{ estado.nombre }}</option>
                    {% endfor %}
                </select>
            </div>

        </div>
        <div class="row">
            <div class="col" style="margin-top:15px;margin-bottom:15px;">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-sm" id="estudiantesTable">
                        <caption class="text-body"><br></caption>
                        <thead>
                        <tr>
                            <th>N°</th>
                            <th>Carnet</th>
                            <th>Nombre</th>
                            <th>Ingreso</th>
                            <th>Estado</th>
                            <th>CUM de Ingreso</th>
                            <th style="text-align: center">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for estudianteP in estudiantes_periodos %}
                            <tr>
                                <td style="text-align: center"></td>
                                <td><a href="{{ path('rotacion_individual',{'carnet':estudianteP.estudiantePlanEstudio.estudiante.carnet})}}">{{ estudianteP.estudiantePlanEstudio.estudiante.carnet }}</a></td>
                                <td>{{ estudianteP.estudiantePlanEstudio.estudiante.persona.nombreCompleto }}</td>
                                <td>{{ estudianteP.estudiantePlanEstudio.estudiante.creado|date('d-M-Y') }}</td>
                                <td>{{ estudianteP.estudianteEstado.nombre }}</td>
                                <td>{{ estudianteP.estudiantePlanEstudio.cum }}</td>
                                <td width="300px">
                                    <div class="btn-group" role="group">
                                        <form action="{{ path('estudiante_estado') }}" method="post">
                                            <input type="hidden" name="id_estudiante_curso" value="{{ estudianteP.id }}"/>
                                            <div class="btn-group" role="group">
                                                <select class="form-control" id="estado" name="id_estado">
                                                    {% for estado in estados %}
                                                        {% if estado.tipo=='curso' %}
                                                            <option value="{{ estado.id }}"
                                                                    {% if estado.id==estudianteP.estudianteEstado.id %}selected="selected" {% endif %}>
                                                                {{ estado.nombre }}
                                                            </option>
                                                        {% endif %}
                                                    {% endfor %}
                                                </select>
                                            </div>
                                            <div class="btn-group" role="group">
                                                <button class="btn btn-info" type="submit">
                                                    <i class="fa fa-angle-right"></i></button>
                                            </div>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    {% else %}
        <div class="col-md-12 offset-md-0" style="margin-top:25px;margin-left:-6px;">
            <h3 style="color: #6E0000">No existen estudiantes aptos para inscribir en el curso seleccionado</h3>
        </div>
    {% endif %}

{% endblock %}

{% block javascripts %}

    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            var t =   $('#estudiantesTable').DataTable({
                "oLanguage": {
                    "sInfoFiltered": "",
                    "sInfo": ""
                },
                "order": [[ 1, "asc" ]],
            });
            t.on( 'order.dt search.dt', function () {
                t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                    cell.innerHTML = i+1;
                } );
            } ).draw();

            $('input.column_filter').on( 'keyup click', function () {
                console.log( $(this).parents('tr').attr('data-column'));
                filterColumn( $(this).parents('tr').attr('data-column') );
            } );


            $('.filter-select').on('change', function() {
                console.log(  $(this).attr('data-column') );
                console.log(this.value)
                $('#estudiantesTable').DataTable().column( $(this).attr('data-column') ).search(
                    this.value
                ).draw();

            })


        } );
    </script>

{% endblock %}

templates/academico/estudiante/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Estudiantes - New{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/myestilos/botonFlotante.css') }}">
    <link rel="stylesheet" href="{{ asset('css/fontawesome-all.min.css') }}">
{% endblock %}
{% block content %}
    <div class="col-md-12 offset-md-0" style="margin-top:25px;margin-left:-6px;">
        <h1>Nomina Oficial a &nbsp;Rotar&nbsp;<br></h1>
        <h5 class="text-muted">Ciclo Par &nbsp;| Numero de estudiantes: 45</h5>
    </div>

    <h2 class="text-center">Perfil de Estudiantes</h2>
    <h3 class="text-left">Fernando Eduardo Bolanos Canjura&nbsp;<small>BC11023</small></h3>
    <h3 class="text-center"></h3>
    <div class="row">
        <div class="col-6 offset-0"><img src="" width="100%" style="width:304px;">
            
        </div>
        <div class="col-6">
            <form>
                <div class="form-group"><label for="apreciacion"><strong>Estado</strong></label><select class="form-control" disabled="" readonly="" id="apreciacion"><option value="12" selected="">Activo</option></select></div>
                <div class="form-group"><label for="apreciacion"><strong>Apreciacion</strong></label><select class="form-control" id="apreciacion"><option value="12" selected="">Excelente</option><option value="13">Muy Buena</option><option value="14">Buena</option></select></div>
                <div
                        class="form-group"><label for="apreciacion"><strong>Departamento</strong></label><select class="form-control" name="Cuscatlan" id="apreciacion"><option value="12" selected="">San Salvador</option><option value="13">La Libertad</option><option value="14">Cuscatlan</option></select></div>
                <div
                        class="form-group"><label for="apreciacion"><strong>Municipio</strong></label><select class="form-control" id="apreciacion"><option value="12" selected="">Apopa</option><option value="13">Santa Tecla</option><option value="14">Cojutepeque</option></select></div>
            </form><button class="btn btn-primary btn-block" type="button">Confirmar</button></div>
    </div>

{% endblock %}