src/Entity/Administracion/Catalogo.php
<?php

namespace App\Entity\Administracion;

use Doctrine\ORM\Mapping as ORM;

/**
 * Catalogo
 *
 * @ORM\Table(name="odontoped_administracion.catalogo", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="codigo", columns={"codigo"})
 * }, indexes={
 *     @ORM\Index(name="fk_catalogo_tipo", columns={"id_catalogo_tipo"}),
 *     @ORM\Index(name="fk_catalogo_padre", columns={"id_padre"})
 * })
 * @ORM\Entity
 */
class Catalogo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="codigo", type="string", length=50, nullable=false)
     */
    private $codigo;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=255, nullable=false)
     */
    private $nombre;

    /**
     * @var string|null
     *
     * @ORM\Column(name="descripcion", type="string", length=500, nullable=true)
     */
    private $descripcion;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var CatalogoTipo
     *
     * @ORM\ManyToOne(targetEntity="CatalogoTipo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_catalogo_tipo", referencedColumnName="id")
     * })
     */
    private $catalogo_tipo;

    /**
     * @var Catalogo
     *
     * @ORM\ManyToOne(targetEntity="Catalogo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_padre", referencedColumnName="id")
     * })
     */
    private $padre;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    /**
     * @param string $codigo
     * @return Catalogo
     */
    public function setCodigo(string $codigo): Catalogo
    {
        $this->codigo = $codigo;
        return $this;
    }

    /**
     * @return string
     */
    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    /**
     * @param string $nombre
     * @return Catalogo
     */
    public function setNombre(string $nombre): Catalogo
    {
        $this->nombre = $nombre;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    /**
     * @param null|string $descripcion
     * @return Catalogo
     */
    public function setDescripcion(?string $descripcion): Catalogo
    {
        $this->descripcion = $descripcion;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return Catalogo
     */
    public function setCreado(\DateTime $creado): Catalogo
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return CatalogoTipo
     */
    public function getCatalogoTipo(): ?CatalogoTipo
    {
        return $this->catalogo_tipo;
    }

    /**
     * @param CatalogoTipo $catalogo_tipo
     * @return Catalogo
     */
    public function setCatalogoTipo(CatalogoTipo $catalogo_tipo): Catalogo
    {
        $this->catalogo_tipo = $catalogo_tipo;
        return $this;
    }

    /**
     * @return Catalogo
     */
    public function getPadre(): ?Catalogo
    {
        return $this->padre;
    }

    /**
     * @param Catalogo $padre
     * @return Catalogo
     */
    public function setPadre(Catalogo $padre): Catalogo
    {
        $this->padre = $padre;
        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): ?string
    {
        return (string)$this->nombre;
    }

}

src/Entity/Administracion/CatalogoTipo.php
<?php

namespace App\Entity\Administracion;

use Doctrine\ORM\Mapping as ORM;

/**
 * CatalogoTipo
 *
 * @ORM\Table(name="odontoped_administracion.catalogo_tipo", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="codigo", columns={"codigo"})
 * }, indexes={
 *     @ORM\Index(name="fk_catalogo_tipo_padre", columns={"id_padre"})
 * })
 * @ORM\Entity
 */
class CatalogoTipo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="codigo", type="string", length=50, nullable=false)
     */
    private $codigo;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=255, nullable=false)
     */
    private $nombre;

    /**
     * @var string|null
     *
     * @ORM\Column(name="descripcion", type="string", length=500, nullable=true)
     */
    private $descripcion;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var CatalogoTipo
     *
     * @ORM\ManyToOne(targetEntity="CatalogoTipo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_padre", referencedColumnName="id")
     * })
     */
    private $padre;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    /**
     * @param string $codigo
     * @return CatalogoTipo
     */
    public function setCodigo(string $codigo): CatalogoTipo
    {
        $this->codigo = $codigo;
        return $this;
    }

    /**
     * @return string
     */
    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    /**
     * @param string $nombre
     * @return CatalogoTipo
     */
    public function setNombre(string $nombre): CatalogoTipo
    {
        $this->nombre = $nombre;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    /**
     * @param string $descripcion
     * @return CatalogoTipo
     */
    public function setDescripcion(string $descripcion): CatalogoTipo
    {
        $this->descripcion = $descripcion;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return CatalogoTipo
     */
    public function setCreado(\DateTime $creado): CatalogoTipo
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return CatalogoTipo
     */
    public function getPadre(): ?CatalogoTipo
    {
        return $this->padre;
    }

    /**
     * @param CatalogoTipo $padre
     * @return CatalogoTipo
     */
    public function setPadre(?CatalogoTipo $padre): CatalogoTipo
    {
        $this->padre = $padre;
        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): ?string
    {
        return (string)$this->nombre;
    }

}

src/Entity/Administracion/Cuenta.php
<?php

namespace App\Entity\Administracion;

use Doctrine\ORM\Mapping as ORM;

/**
 * Cuenta
 *
 * @ORM\Table(name="odontoped_administracion.cuenta")
 * @ORM\Entity
 */
class Cuenta
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return Cuenta
     */
    public function setCreado(\DateTime $creado): Cuenta
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): ?string
    {
        if ($this->creado)
            return (string)$this->getId() . ' - ' . $this->creado->format('Y-m-d H:i:s');
        else
            return (string)$this->getId();
    }


}

src/Entity/Administracion/Persona.php
<?php

namespace App\Entity\Administracion;

use Doctrine\ORM\Mapping as ORM;

/**
 * Persona
 *
 * @ORM\Table(name="odontoped_administracion.persona", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="dui", columns={"dui"}),
 *     @ORM\UniqueConstraint(name="nit", columns={"nit"})
 * }, indexes={
 *     @ORM\Index(name="fk_persona_cuenta", columns={"id_cuenta"})
 * })
 * @ORM\Entity
 */
class Persona
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=50, nullable=false)
     */
    private $nombre;

    /**
     * @var string|null
     *
     * @ORM\Column(name="apellido", type="string", length=50, nullable=true)
     */
    private $apellido;

    /**
     * @var string|null
     *
     * @ORM\Column(name="dui", type="string", length=10, nullable=true)
     */
    private $dui;

    /**
     * @var string|null
     *
     * @ORM\Column(name="dui_apoderado", type="string", length=12, nullable=true)
     */
    private $dui_apoderado;

    /**
     * @var string|null
     *
     * @ORM\Column(name="centro_educativo_paciente", type="string", length=500, nullable=true)
     */
    private $centro_educativo_paciente;

    /**
     * @var string|null
     *
     * @ORM\Column(name="nit", type="string", length=17, nullable=true)
     */
    private $nit;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="nacimiento", type="date", nullable=true)
     */
    private $nacimiento;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creado", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $creado;

    /**
     * @var Cuenta
     *
     * @ORM\ManyToOne(targetEntity="Cuenta")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_cuenta", referencedColumnName="id")
     * })
     */
    private $cuenta;

    /**
     * @var string|null
     *
     * @ORM\Column(name="archivo_consentimiento", type="string", length=999, nullable=true)
     */
    private $archivo_consentimiento;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    /**
     * @param string $nombre
     * @return Persona
     */
    public function setNombre(string $nombre): Persona
    {
        $this->nombre = $nombre;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getApellido(): ?string
    {
        return $this->apellido;
    }

    /**
     * @param null|string $apellido
     * @return Persona
     */
    public function setApellido(?string $apellido): Persona
    {
        $this->apellido = $apellido;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getDui(): ?string
    {
        return $this->dui;
    }

    /**
     * @param null|string $dui
     * @return Persona
     */
    public function setDui(?string $dui): Persona
    {
        $this->dui = $dui;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getDuiApoderado(): ?string
    {
        return $this->dui_apoderado;
    }

    /**
     * @param null|string $dui_apoderado
     * @return Persona
     */

    public function setDuiApoderado(?string $dui_apoderado): Persona
    {
        $this->dui_apoderado = $dui_apoderado;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getCentroEducativo(): ?string
    {
        return $this->centro_educativo_paciente;
    }


    /**
     * @param null|string $centro_educativo_paciente
     * @return Persona
     */
    public function setCentroEducativo(?string $centro_educativo_paciente): Persona
    {
        $this->centro_educativo_paciente = $centro_educativo_paciente;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getNit(): ?string
    {
        return $this->nit;
    }

    /**
     * @param null|string $nit
     * @return Persona
     */
    public function setNit(?string $nit): Persona
    {
        $this->nit = $nit;
        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getNacimiento(): ?\DateTime
    {
        return $this->nacimiento;
    }

    /**
     * @param \DateTime|null $nacimiento
     * @return Persona
     */
    public function setNacimiento(?\DateTime $nacimiento): Persona
    {
        $this->nacimiento = $nacimiento;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreado(): ?\DateTime
    {
        return $this->creado;
    }

    /**
     * @param \DateTime $creado
     * @return Persona
     */
    public function setCreado(\DateTime $creado): Persona
    {
        $this->creado = $creado;
        return $this;
    }

    /**
     * @return Cuenta
     */
    public function getCuenta(): ?Cuenta
    {
        return $this->cuenta;
    }

    /**
     * @param Cuenta $cuenta
     * @return Persona
     */
    public function setCuenta(Cuenta $cuenta): Persona
    {
        $this->cuenta = $cuenta;
        return $this;
    }

    /**
     * @return string
     */
    public function getArchivoConsentimiento(): ?string
    {
        return $this->$archivo_consentimiento;
    }

    /**
     * @param string $archivo_consentimiento
     * @return Persona
     */
    public function setArchivoConsentimiento(string $archivo_consentimiento): Persona
    {
        $this->archivo_consentimiento = $archivo_consentimiento;
        return $this;
    }

    /**
     * @return string
     */
    public function getNombreCompleto(): string
    {
        return $this->nombre . ' ' . $this->apellido;
    }

    /**
     * @return string
     */
    public function __toString(): ?string
    {
        return (string)$this->getNombreCompleto();
    }

    /**
     * @return string
     */
    public function getTipoPaciente(): ?string
    {
        $tipo = null;
        if ($this->nacimiento) {
            $edad = (new \DateTime())->diff($this->nacimiento)->y;
            if ($edad < 12) $tipo = 'Niño';
            else if ($edad < 18) $tipo = 'Adolescente';
            else $tipo = 'Adulto';
        }

        return $tipo;
    }





}

src/Form/Administracion/PersonaType.php
<?php

namespace App\Form\Administracion;

use App\Entity\Administracion\Persona;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('apellido')
            ->add('dui', null, ['label' => 'DUI'])
            ->add('nit', null, ['label' => 'NIT'])
            ->add('nacimiento', null, ['widget' => 'single_text']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Persona::class,
        ]);
    }
}

src/Controller/Administracion/MenuController.php
<?php

namespace App\Controller\Administracion;

use App\Entity\Administracion\Menu;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class MenuController
 * @package App\Controller\Administracion
 * @Route("/menu")
 */
class MenuController extends AbstractController
{
    /**
     * @Route("/{menu}", name="menu_submenus")
     * @param Menu $menu
     * @return Response
     */
    public function submenus(Menu $menu)
    {
        $em = $this->getDoctrine();
        $submenus = $em->getRepository('Administracion:Menu')
            ->findBy(['padre' => $menu]);
        return $this->render('administracion/menu/submenus.html.twig', [
            'menu' => $menu,
            'submenus' => $submenus,
        ]);
    }
}

templates/administracion/perfil/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<div class="form-group">
    <button class="btn btn-primary">Guardar</button>
</div>
{{ form_end(form) }}

templates/administracion/perfil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Perfil{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ path('perfil') }}">Perfil</a></li>
    <li class="breadcrumb-item active" aria-current="page">Editar</li>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-2 text-center">
            <img src="//placehold.it/160" class="avatar m-x-auto img-fluid img-circle" alt="avatar">
        </div>
        <div class="col-md-10">
            <h4 class="text-center">{{ persona.nombreCompleto }}</h4>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#" data-target="#profile" data-toggle="tab" class="nav-link active">Editar perfil</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="profile">
                    <div class="row">
                        <div class="col-md-12">
                            {{ include('administracion/perfil/_form.html.twig') }}
                            <div class="form-group">
                                <a href="{{ path('perfil') }}" class="btn btn-link btn-outline-primary">Regresar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/administracion/perfil/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Perfil{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ path('perfil') }}">Perfil</a></li>
    <li class="breadcrumb-item active" aria-current="page">Nuevo</li>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-2 text-center">
            <img src="//placehold.it/160" class="avatar m-x-auto img-fluid img-circle" alt="avatar">
        </div>
        <div class="col-md-10">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#" data-target="#profile" data-toggle="tab" class="nav-link active">Nuevo perfil</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="profile">
                    <div class="row">
                        <div class="col-md-12">
                            {{ include('administracion/perfil/_form.html.twig') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/administracion/perfil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Perfil{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Perfil</li>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-2 text-center">
            <img src="//placehold.it/160" class="avatar m-x-auto img-fluid img-circle" alt="avatar">
            <label class="control-label">
                <input type="file" id="avatar" class="d-none custom-file-input">
                {#<span class="btn btn-link">Cambiar</span>#}
            </label>
        </div>
        <div class="col-md-10">
            <h4 class="text-center">{{ persona.nombreCompleto }}</h4>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#" data-target="#profile" data-toggle="tab" class="nav-link active">Perfil</a>
                </li>
                <li class="nav-item">
                    <a href="#" data-target="#contact" data-toggle="tab" class="nav-link">Contacto</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="profile">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover table-striped">
                                <tbody>
                                <tr>
                                    <th>Nombre</th>
                                    <td>{{ persona.nombre }}</td>
                                </tr>
                                <tr>
                                    <th>Apellido</th>
                                    <td>{{ persona.apellido }}</td>
                                </tr>
                                <tr>
                                    <th>DUI</th>
                                    <td>{{ persona.dui }}</td>
                                </tr>
                                <tr>
                                    <th>NIT</th>
                                    <td>{{ persona.nit }}</td>
                                </tr>
                                <tr>
                                    <th>Nacimiento</th>
                                    <td>{{ persona.nacimiento? persona.nacimiento|date('Y-m-d') : '' }}</td>
                                </tr>
                                </tbody>
                            </table>

                            <a href="{{ path('perfil_edit') }}">Editar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}